### ISSUE TITLE
server errors on start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [trdlo/client175#11]
```
When I run 'python server.py' the server does not start.  Instead, I get this 
error output:

Traceback (most recent call last):
  File "server.py", line 47, in <module>
    mpd = mpd_proxy.Mpd()
  File "/var/www/localhost/htdocs/client175/mpd_proxy2.py", line 52, in Mpd
    _Instance = _Mpd_Instance(**kwargs)
  File "/var/www/localhost/htdocs/client175/mpd_proxy2.py", line 174, in __init__
    self._connect()
  File "/var/www/localhost/htdocs/client175/mpd_proxy2.py", line 204, in _connect
    self.con.connect(self._host, self._port)
  File "/var/www/localhost/htdocs/client175/mpd.py", line 338, in connect
    self._sock = self._connect_tcp(host, port)
  File "/var/www/localhost/htdocs/client175/mpd.py", line 329, in _connect_tcp
    raise socket.error(msg)
socket.error: [Errno 111] Connection refused

I don't see any place to enter the port which MPD is using, could this be the 
problem?
```

Original issue reported on code.google.com by `campbell...@gmail.com` on 30 Jun 2010 at 3:41
- Merged into: #8

**Comment by GoogleCodeExporter** [comment]
```
The server uses the same MPD_HOST and MPD_PORT environment variables that mpc 
uses.  To set the port to something other than 6600, run this command prior to 
starting the server:

export MPD_PORT=6600

I plan on adding configurations options to the site.conf file.  The resoltuon 
for this will be the same as issue 8.
```

Original comment by `cseic...@gmail.com` on 30 Jun 2010 at 2:38
- Changed state: **Duplicate**
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**
