### ISSUE TITLE
Playlist is always empty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [trdlo/client175#25]
```
What steps will reproduce the problem?
1. Use the web UI to navigate to any kind of song (saved playlist, via artist 
or genre)
2. Press either the green + button near a song or the "+Add All" button at the 
top of the list.
The Playlist in the sidebar on the right is not populated (nothing is 
displayed/empty), but pressing the "play" button starts playback normally.

What is the expected output? What do you see instead?

The Playlist in the sidebar on the right is not populated (nothing is 
displayed/empty), but pressing the "play" button starts playback normally.

The following error is logged:

HTTP Traceback (most recent call last):
  File "/opt/client175/cherrypy/_cprequest.py", line 606, in respond
    cherrypy.response.body = self.handler()
  File "/opt/client175/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "server.py", line 468, in query
    pl = mpd.getPlaylistByFile(d['file'])
  File "/opt/client175/mpd_proxy2.py", line 265, in getPlaylistByFile
    item = self._extendDbResult(pl)[0]
  File "/opt/client175/mpd_proxy2.py", line 160, in __getattr__
    fn = getattr(self.con, name)
  File "/opt/client175/mpd.py", line 188, in __getattr__
    (self.__class__.__name__, attr))
AttributeError: 'MPDClient' object has no attribute '_extendDbResult'


Please use labels and text to provide additional information.

Using another mpd client reveals that the current playlist is actually 
modified, only nothing is displayed in the client175 UI.

I am using Puppy Linux 5.1.1 with XAMPP 1.7.3a and Python 2.6

In the attached screenshot, I am showing client175 and GMPC at the same time 
connected to the same mpd server. On GMPC the playlist is populated while in 
client175 it's empty.

Thanks in advance for help.
```

Original issue reported on code.google.com by `buralien` on 16 Nov 2010 at 8:06

Attachments:
- [client175 vs GMPC.png](https://storage.googleapis.com/google-code-attachments/client175/issue-25/comment-0/client175 vs GMPC.png)

**Comment by GoogleCodeExporter** [comment]
```
That error seems to indicate that you have a different version of the mpd.py 
file than came with that release.  Can you try downloading the client again and 
overwriting those files?

```

Original comment by `cseic...@gmail.com` on 17 Nov 2010 at 10:31

**Comment by GoogleCodeExporter** [comment]
```
Hello,

I re-downloaded version 0.3, checked SHA1 checksum, extracted, modified the 
server name in the .conf file and started. I have the same error.

```

Original comment by `buralien` on 19 Nov 2010 at 11:20

**Comment by GoogleCodeExporter** [comment]
```
I finally figured this out.  The bug depended on browsing a location that had 
enough files to trigger paging, which lead to old code that I hadn't tested in 
a while.

This has been cleaned up and a new release is posted in the Downloads section 
(0.4).
```

Original comment by `cseic...@gmail.com` on 20 Nov 2010 at 5:50
- Changed state: **Fixed**
