### ISSUE TITLE
Lots of 500's site half broken but still partially works

### ISSUE THREAD

**Issue by GoogleCodeExporter** [trdlo/client175#48]
```
What steps will reproduce the problem?
1. Install following apache instructions
2. Connect to client175
3. View error log

What is the expected output? What do you see instead?

The errorlog has lots of these errors:

[14/Feb/2013:10:57:25] MOD_PYTHON Traceback (most recent call last):
  File "/home/music/client175/cherrypy/_cpmodpy.py", line 139, in handler
    setup(req)
  File "/home/music/client175/cherrypy/_cpmodpy.py", line 82, in setup
    mod = __import__(modname, globals(), locals(), [fname])
  File "/home/music/client175/server.py", line 76, in <module>
    mpd = mpd_proxy.Mpd(HOST, PORT, PASSWORD)
  File "/home/music/client175/mpd_proxy2.py", line 48, in Mpd
    _Instance = _Mpd_Instance(host, port, password)
  File "/home/music/client175/mpd_proxy2.py", line 144, in __init__
    self._connect()
  File "/home/music/client175/mpd_proxy2.py", line 157, in _connect
    self.con.connect(self._host, self._port, self._password)
  File "/home/music/client175/mpd.py", line 423, in connect
    self._hello()
  File "/home/music/client175/mpd.py", line 366, in _hello
    raise ConnectionError("Connection lost while reading MPD hello")
ConnectionError: Connection lost while reading MPD hello

The UI mostly works - the playlist *sometimes* doesn't show, same with the 
track/album info, though if i look in the webbrowser's debugger i can see 500's 
all over the place:

GET http://music.0xff.co.uk/static/ext/resources/css/xtheme-slate.css 500 
(Internal Server Error) index.html:39
POST http://music.0xff.co.uk/playlistinfoext 500 (Internal Server Error) 
ext-base.js:7
GET 
http://music.0xff.co.uk/covers?file=1stgig-bits%2F%5BOZC%5DGhost%20in%20the%20Sh
ell%20Stand%20Alone%20Complex%20Clean%20OP%20(Alternate%20Broadcast%20Ver.).mp4&
artist=&album= 500 (Internal Server Error) ext-all-debug.js:451
POST http://music.0xff.co.uk/lyrics 500 (Internal Server Error) ext-base.js:7

As far as i can tell the error in the apache logs are the same for each 500 
regardless of which request is made.

Here is my site.log: http://paste.ubuntu.com/1649604/
Here is my site.conf: http://paste.ubuntu.com/1649623/
Here is my apache config: http://paste.ubuntu.com/1649647/

Thanks in advance,

Paul

```

Original issue reported on code.google.com by `paul.a.g...@gmail.com` on 14 Feb 2013 at 11:15

**Comment by GoogleCodeExporter** [comment]
```
That is an unusual collection of errors in your log.  The lyricwiki stuff could 
very well be broken so it can be ignored.  The errors about db_playtime and 
playlistlength should never happen.  The lsinfo errors could be due to escaping 
of special characters in the the client --> apache --> python script pipeline.  
Can you tell me a little more about your setup?

1.  Where is mpd in relation to the web server?  Same computer, or different 
computer but same network?
2.  What version of mpd are you running?

To determine if it is an issue with the Apache setup, can you try running 
client175 with the builtin server and see if you get the same errors?
```

Original comment by `cseic...@gmail.com` on 14 Feb 2013 at 12:17

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your reply,

1. mpd is running on the same machine as the web server.
2. mpd 0.16.2

This machine hosts a handfull of services and already has apache installed, so 
ideally i want to use apache vhosts - as per the configuration posted in the OP.

client175 is installed into /home/music/client175

I realized that the site.log i posted in the OP probably had misleading error 
messages in it, as there were errors that i had already resolved (no password 
in configuration) however it looks like you've identified the reliant ones 
correctly.

In anycase, i started a fresh log file and restarted the application. here is 
the fresh log: http://paste.ubuntu.com/1652381

I've also just tried running on the python webserver as you suggested and it 
runs great, so i can only presume its something unique with my apache install.

The server is hosting maybe 10 different websites and has various modules 
installed - I'm going to investigate and see if I can find out whats causing 
the issue.

```

Original comment by `paul.a.g...@gmail.com` on 14 Feb 2013 at 5:05
