### ISSUE TITLE
No Covers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [trdlo/client175#51]
```
What steps will reproduce the problem?
1. Get from svn checkout http://client175.googlecode.com/svn/trunk/ 
client175-read-only

What is the expected output? What do you see instead?
Open /var/www/site.log

[15/Apr/2013:17:32:49] HTTP Traceback (most recent call last):
  File "/var/www/cherrypy/_cprequest.py", line 606, in respond
    cherrypy.response.body = self.handler()
  File "/var/www/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/var/www/server.py", line 213, in default
    result = mpd.execute(args)
  File "/var/www/mpd_proxy2.py", line 235, in execute
    return getattr(self, cmd)(*cmdlist)
  File "/var/www/mpd_proxy2.py", line 167, in __getattr__
    fn = getattr(self.con, name)
  File "/var/www/mpd.py", line 188, in __getattr__
    (self.__class__.__name__, attr))
AttributeError: 'MPDClient' object has no attribute 'covers.pyc'
```

Original issue reported on code.google.com by `b...@neoline.ru` on 15 Apr 2013 at 1:44

**Comment by GoogleCodeExporter** [comment]
```
mpd (MPD: Music Player Daemon) 0.16.5

Server version: Apache/2.2.22 (Ubuntu)
Server built:   Mar  8 2013 15:53:14

Linux srv-mdp 3.5.0-23-generic #35~precise1-Ubuntu SMP Fri Jan 25 17:15:33 UTC 
2013 i686 i686 i386 GNU/Linux

Python 2.7.3

```

Original comment by `b...@neoline.ru` on 15 Apr 2013 at 2:09
